---
title: "Getting Started with BTSBM"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting Started with BTSBM}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.align = "center",
  warning = FALSE,
  message = FALSE
)
set.seed(123)
```

This vignette shows a lightweight workflow for fitting a Bradley-Terry stochastic
block model and producing core summaries.

```{r}
library(BTSBM)
```

## Data

```{r}
w_ij <- ATP_2000_2025$`2017`$Y_ij[1:12, 1:12]
diag(w_ij) <- 0L
w_ij[1:3, 1:3]
```

## Fit

```{r}
fit <- gibbs_bt_sbm(
  w_ij = w_ij,
  a = 2,
  prior = "GN",
  gamma_GN = 0.8,
  T_iter = 200,
  T_burn = 100,
  verbose = FALSE
)
```

## Relabel and Summarise

```{r}
post <- relabel_by_lambda(fit$x_samples, fit$lambda_samples)
pretty_table_K_distribution(post)
```

## Core Plots

```{r, fig.width = 8, fig.height = 5}
plot_block_adjacency(fit = post, w_ij = w_ij)
```

```{r, fig.width = 8, fig.height = 6}
plot_assignment_probabilities(fit = post, w_ij = w_ij, x_hat = post$minVI_partition)
```

```{r, fig.width = 8, fig.height = 6}
plot_lambda_uncertainty(fit = post, w_ij = w_ij, x_hat = post$minVI_partition)
```

```{r, fig.width = 8, fig.height = 6}
plot_rank_intervals(post, max_players = 12)
```
