# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Update cluster assignments and row sums
#'
#' Internal helper used by the Gibbs sampler to update latent cluster
#' assignments and the corresponding row-sum summaries.
#'
#' @param n_ij Integer matrix of pairwise match counts.
#' @param x Integer vector of current cluster assignments.
#' @param lambda Numeric vector of current item strengths.
#' @keywords internal
updateZ_and_rowsums <- function(n_ij, x, lambda) {
    .Call(`_BTSBM_updateZ_and_rowsums`, n_ij, x, lambda)
}

