# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'  @keywords internal
updateZ_and_rowsums <- function(n_ij, x, lambda) {
    .Call(`_BTSBM_updateZ_and_rowsums`, n_ij, x, lambda)
}

